import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';

const CartProductPage: NextPage = () => {
    return (
        <>
            <Head>
                <title>Cart</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>Trang giỏ hàng</h1>
            </div>
        </>
    );
};

export default CartProductPage;