import { wrapper } from '@/app/store';
import ListProduct from '@/components/ListProduct/ListProduct';
import { getListProduct, getListSortProduct, selectCollectionEcommerceSelector } from '@/features';
import { NextPage } from 'next';
import Head from 'next/head'
import { Container, Flex, Group, Tabs, Space } from '@mantine/core';
import IconListCart from '@/components/IconCart/IconListCart';
import IconListHeart from '@/components/IconHeart/IconListHeart';
import SearchProduct from '@/components/SearchProduct/SearchProduct';
import Image from 'next/image';
import { useAppDispatch, useAppSelector } from '@/app/hooks';
import PaginationProduct from '@/components/PaginationProduct/PaginationProduct';

const Home: NextPage = () => {
  const dispatch = useAppDispatch()
  const { newFilterSearchList } = useAppSelector(selectCollectionEcommerceSelector);
  console.log("xem: ", newFilterSearchList);

  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid>
        <Flex
          mih={70}
          gap="md"
          justify="space-between"
          align="center"
          direction="row"
          wrap="wrap"
          className='py-3'
        >
          <Image src={`/next.svg`} width={100} height={100} alt="logo" />
          <SearchProduct />
          <Group position="right">
            <IconListCart />
            <IconListHeart />
          </Group>
        </Flex>
        <Space h="md" />
        <Tabs
          keepMounted={false} defaultValue="all"
          onTabChange={(value: string) => dispatch(getListSortProduct(value))}
        >
          <Tabs.List>
            <Tabs.Tab value="all">Phổ biến</Tabs.Tab>
            <Tabs.Tab value="price asc">Giá Thấp Đến Cao</Tabs.Tab>
            <Tabs.Tab value="price desc">Giá Cao Đến Thấp</Tabs.Tab>
          </Tabs.List>
          <Space h="md" />
          <Tabs.Panel value="all">
            <ListProduct />
          </Tabs.Panel>
          <Tabs.Panel value="price asc">
            <ListProduct />
          </Tabs.Panel>
          <Tabs.Panel value="price desc">
            <ListProduct />
          </Tabs.Panel>
        </Tabs>
      </Container>
      <Space h="md" />
      {newFilterSearchList?.length > 0 && (
        <PaginationProduct total={newFilterSearchList?.length} />
      )}
    </>
  )
}
Home.getInitialProps = wrapper.getInitialPageProps(({ dispatch }) => async () => {
  await dispatch(getListProduct())
})
export default Home