
import { wrapper } from '@/app/store';
import ListProduct from '@/components/ListProduct/ListProduct';
import { getListProduct } from '@/features';
import { NextPage } from 'next';
import Head from 'next/head'
import { Container } from '@mantine/core';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid className='bg-[#efefef]'>
        <ListProduct />
      </Container>
    </>
  )
}
Home.getInitialProps = wrapper.getInitialPageProps(({ dispatch }) => async () => {
  await dispatch(getListProduct())
})
export default Home