import ProductLikesList from '@/components/ProductLikesList/ProductLikesList';
import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { Container } from '@mantine/core';

const Likes: NextPage = () => {
    return (
        <>
            <Head>
                <title>Favorite Product</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container fluid>
                <ProductLikesList />
            </Container>
        </>
    );
};

export default Likes;